version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: ilya
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app42

  adminer:
    build:
      context: .
    ports:
      - 8080:8080
