version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  adminer:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
