version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  adminer:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: data_volume
        target: /var/lib/tomcat9/webapps
    depends_on:
      - db

volumes:
  data_volume: